Added support for the use of secure tokens
koala-interactive/wowza-webrtc-player pull request #20
Opened 2022-09-21 14:53 UTC by dominik-pre

Added support as described in:
https://www.wowza.com/docs/how-to-protect-streaming-using-securetoken-in-wowza-streaming-engine

2022-10-18 16:27 UTC, vthibault requested changes
Hi,
I didn't know about this feature, thank you for your time!

I have some little modifications but the whole code is great 👍

2022-10-18 16:27 UTC, vthibault commented on .gitignore
> -dist
`dist` should still be listed to avoid the folder to be commit.
At the same time, you should remove it the `dist` folder you sent on this PR

2022-10-18 16:27 UTC, vthibault commented on src/wowza/wowza.ts
> +    }
Maybe better to have this kind of code:

```ts
const data: TSocketSendData['getOffer'] = {
  direction: 'play',
  command: 'getOffer',
};

if (this.streamInfo.secureToken) {
   data.secureToken = this.streamInfo.secureToken;
}

return this.send<TSocketSendData['getOffer'], TSocketRecvData['getOffer']>(data);
```

2022-10-18 16:27 UTC, vthibault commented on src/webrtc/SDPEnhancer.ts
> +        return `profile-level-id=${((profile << 16) | (constraint << 8) | level).toString(16)}`;
Nice catch 👍

2022-10-27 06:28 UTC, vthibault approved these changes
Awesome!
Thank you for the modifications 👌

2022-10-27 07:56 UTC, besLisbeth commented
@dominik-pre very cool update; I already successfully tested it👍Eagerly waiting for the new update

2022-10-27 12:25 UTC, merged